const v = (prefix) => {
	return `
╭──❲ ATTACK ❳
│• ${prefix}hacked
│• ${prefix}v1
│• ${prefix}bugspasi
│• ${prefix}hen
│• ${prefix}bughole
│• ${prefix}bughole1
│• ${prefix}superhole
│• ${prefix}hen1
│• ${prefix}love
│• ${prefix}granat
│• ${prefix}heli
│• ${prefix}heli1
│• ${prefix}panah
│• ${prefix}bintang
│• ${prefix}tank
│• ${prefix}bugpc
│• ${prefix}bugpc1
│• ${prefix}bugtroli
│• ${prefix}catalog
│• ${prefix}catalogv1
│• ${prefix}virgam
│• ${prefix}virgamv1
│• ${prefix}bugtroli1
│• ${prefix}kodenuklir1
│• ${prefix}kodenuklir2
│• ${prefix}virtex1
│• ${prefix}virtex2
│• ${prefix}virtex3
│• ${prefix}virtex4
│• ${prefix}virtex5
│• ${prefix}virtex6
│• ${prefix}virtex7
│• ${prefix}virtex8
│• ${prefix}virtex9
│• ${prefix}virtex10
│• ${prefix}virtex11
│• ${prefix}virtex12
│• ${prefix}virtex13
│• ${prefix}virtex14
│• ${prefix}virtex15
│• ${prefix}virtex16
│• ${prefix}virtex17
│• ${prefix}virtex18
│• ${prefix}virtex19
│• ${prefix}virtex20
│• ${prefix}virtex21
│• ${prefix}virtex22
│• ${prefix}virtex23
│• ${prefix}virtex24
│• ${prefix}virtex25
│• ${prefix}virtex26
│• ${prefix}virtex27
│• ${prefix}virtex28
│• ${prefix}virtex29
│• ${prefix}virtex30
│• ${prefix}virtex31
│• ${prefix}virtex32
│• ${prefix}virtex33
│• ${prefix}virtex34
│• ${prefix}virtex35
│• ${prefix}virtex36
│• ${prefix}virtex37
│• ${prefix}virtex38
│• ${prefix}virtex39
│• ${prefix}virtex40
│• ${prefix}virtex41
│• ${prefix}virtex42
│• ${prefix}virtex43
│• ${prefix}virtex44
│• ${prefix}virtex45
│• ${prefix}virtex46
│• ${prefix}virtex47
│• ${prefix}virtex48
│• ${prefix}virtex49
│• ${prefix}virtex50
│• ${prefix}virtex51
│• ${prefix}virtex52
│• ${prefix}virtex53
│• ${prefix}virtex54
│• ${prefix}virtex55
│• ${prefix}virtex56
│• ${prefix}virtex57
│• ${prefix}virtex58
│• ${prefix}virtex59
│• ${prefix}virtex60
│• ${prefix}virtex61
│• ${prefix}virtex62
│• ${prefix}virtex63
│• ${prefix}virtex64
│• ${prefix}virtex65
│• ${prefix}virtex66
│• ${prefix}virtex67
│• ${prefix}virtex68
│• ${prefix}virtex69
│• ${prefix}virtex70
│• ${prefix}virtex71
│• ${prefix}virtex72
│• ${prefix}virtex73
│• ${prefix}virtex74
│• ${prefix}virtex75
│• ${prefix}virtex76
│• ${prefix}virtex77
│• ${prefix}virtex78
│• ${prefix}virtex79
│• ${prefix}virtex80
│• ${prefix}virtex81
│• ${prefix}virtex82
│• ${prefix}virtex83
│• ${prefix}virtex84
│• ${prefix}virtex85
│• ${prefix}virtex86
│• ${prefix}virtex87
│• ${prefix}virtex88
│• ${prefix}virtex89
│• ${prefix}virtex90
│• ${prefix}virtex91
│• ${prefix}virtex92
│• ${prefix}virtex93
│• ${prefix}virtex94
│• ${prefix}virtex95
│• ${prefix}virtex96
│• ${prefix}virtex97
│• ${prefix}virtex98
│• ${prefix}virtex99
│• ${prefix}virtex100
╰────────────────⊱
`
}

exports.v = v